apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-elk
  labels:
    component: nest-elk
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: nest-elk
  template:
    metadata:
      labels:
        component: nest-elk
    spec:
      containers:
        - name: nest-elk
          image: edwardpm1206/nest-gcsfuse
          args:
            - sh
            - -c
            - >
              while true;
              do
                echo $(date) - filebeat log >> /var/log/access.log;
                sleep 10;
              done
          volumeMounts:
            - name: log
              mountPath: /var/log
          ports:
            - containerPort: 3000
        - name: filebeat
          image: elastic/filebeat:7.16.3
          args:
            - -c
            - /etc/filebeat/conf.yaml
            - -e
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
